version: 2
jobs:
  test-template:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/template
    steps:
      - checkout
      - run: yarn
      - run: yarn pack:rename
      - run: npx create-react-app ~/template/test-template --scripts-version=/home/circleci/template/jpavon-react-scripts-ts.tgz
      - run: cd ~/template/test-template && yarn test

  test-kitchensink:
    docker:
      - image: circleci/node:8.11.3-browsers
    working_directory: ~/kitchensink
    steps:
      - checkout
      - run: yarn
      - run: yarn pack:rename
      - run: E2E_TEST='true' npx create-react-app ~/kitchensink/test-kitchensink --scripts-version=/home/circleci/kitchensink/jpavon-react-scripts-ts.tgz --internal-testing-template=/home/circleci/kitchensink/fixtures/kitchensink
      - run: cd ~/kitchensink/test-kitchensink && yarn test --maxWorkers=2
      - run: cd ~/kitchensink/test-kitchensink && yarn e2e:dev
      - run: cd ~/kitchensink/test-kitchensink && yarn e2e:build

workflows:
  version: 2
  tests:
    jobs:
      - test-template
      - test-kitchensink
